site_name: FPGA Build System
#site_url: ''
#use_directory_urls: false

extra_css: [extra.css]

theme:
     name: readthedocs
     features:
         - content.code.copy
         - content.code.annotate     
  #  name: windmill

nav:
    - Build System:
        - General             : index.md
        - Build Variants      : Build-Variants.md
        - Build Scripts       : Build-Scripts.md
        - Advanced Topics     : Advanced-Topics.md
    - Reference:
        - Reference           : Reference.md
        - Service API         : Service-API.md
        - Tool Vivado         : Tool-Vivado.md  
        - Tool Questa         : Tool-Questa.md  
    - Examples:
        - Simple                : Simple-Example.md
        - Advandced             : Advanced-Example.md



extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - toc:
        permalink: "🔗"
        baselevel: 3
    - admonition
    - mdx_math
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.details
    - pymdownx.superfences
    - attr_list
    - footnotes
#

plugins:
    - glightbox






